# Generated by Django 3.2.5 on 2021-07-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repo",
            options={"ordering": ("owner", "name")},
        ),
    ]
